name: Code quality

on:
  push:
    branches:
      - main

jobs:
  flake8:
    uses: esantix/workflows/.github/workflows/python_flake8.yml@main
    with:
        ignore-codes: E501,E502

  test:
    uses: esantix/workflows/.github/workflows/python_unittest.yml@main
    with:
      pythonpath: python/src
      testpath: python/src/tests
      requirements: python/requirements.txt
