name: Test esantix/workflows

on:
  push:
    branches:
      - main

jobs:
  python_flake8:
    uses: esantix/workflows/.github/workflows/python_flake8.yml@main
    with:
        ignore-codes: E501,E502

  python_unittest:
    uses: esantix/workflows/.github/workflows/python_unittest.yml@main
    with:
      pythonpath: python/src
      testspath: python/src/tests
      requirements: -r python/requirements.txt

  terraform_test:
    uses: esantix/workflows/.github/workflows/terraform_test.yml@main
    with:
      terraform-wdir: ./terraform
    
    